server:
  port: 8080
name: 我帅得一匹
age: 22
content: "name:${name},age:${age}"
student:
  name: 真的帅
  age: 21
#添加thymeleaf依赖后jsp会报错找不到，要两者同时使用方法如下，templates下新添thy文件夹，返回路径前加thy/
spring:
  thymeleaf:
    view-names: thy/*
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=Utf-8
    username: root
    password: 724111
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  #新增数据库连接必备参数
#文件名必须是application.yml
#  YAML加载属性到内存中保存的时候是有序的
#定义不同环境设置
  #server:
  #    port: 8881
  #---
  #spring:
  #    profiles: test
  #server:
  #    port: 8882
  #---
  #spring:
  #    profiles: prod
  #server:
  #    port: 8883